image: node:8

before_script:
- npm install


# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    
test:
  script:
  - npm run test -- --color=false
  tags:
  - WEB-IHM
  coverage: /All files\s+\|\s+([\d.]+)/